# Generated by Django 5.0.4 on 2024-05-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_lname_item_sname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fname',
        ),
        migrations.AddField(
            model_name='item',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
