# Generated by Django 5.0.4 on 2024-05-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_fname_item_lname_alter_item_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lname',
            new_name='fname',
        ),
    ]
